name 'chef-provisioning-aws-helper'
maintainer 'Irving Popovetsky'
maintainer_email 'irving@chef.io'
license 'all_rights'
description 'Installs/Configures chef-provisioning-aws-helper'
long_description 'Installs/Configures chef-provisioning-aws-helper'
version '0.2.0'
source_url       'https://github.com/irvingpop/chef-provisioning-aws-helper'
issues_url       'https://github.com/irvingpop/chef-provisioning-aws-helper/issues'

depends 'lvm'
